VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "JSONOutput"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Sub WriteText(Text As String)
    ' write Text + VbCrLf
End Sub

Public Sub WriteLine(Text As String)
    ' write Text + VbCrLf
End Sub

Public Sub CrLf()
    ' write vbCrLf
End Sub
